// Bilingual content + data

window.PORTFOLIO_CONTENT = {
  profile: {
    name: "VLADISLAV_",
    handle: "@nekopunk44",
    location: "Tiraspol, MD",
    years: "2+",
    telegram: "@van_g0ck",
    whatsapp: "+373 775 148 90",
    github: "https://github.com/nekopunk44",
    email: "vladbredihin4@gmail.com",
  },
  i18n: {
    ru: {
      nav: ["~/home", "~/about", "~/stack", "~/cases", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "Проектирую и собираю сайты, мобильные приложения и 3D-сцены. От идеи до прод-деплоя — в одних руках.",
      heroCta: "начать диалог",
      heroSecondary: "скачать краткое CV",
      status: "СВОБОДЕН ДЛЯ ЗАКАЗОВ",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ОБО МНЕ",
        stack: "02 / СТЕК",
        cases: "03 / КЕЙСЫ",
        process: "04 / ПРОЦЕСС",
        timeline: "05 / ОПЫТ",
        faq: "06 / FAQ",
        contact: "07 / СВЯЗЬ",
      },
      marquee: [
        "2+ лет в продакшене",
        "fullstack · web · mobile · 3d",
        "от идеи до deploy",
        "ответ в течение дня",
        "работаю удалённо",
        "русский · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "Как я работаю",
        steps: [
          { n: "01", t: "Brief", d: "Обсуждаем задачу, цели и ограничения. Задаю правильные вопросы.", tools: "call · текст · figma" },
          { n: "02", t: "Spec", d: "Составляю техническое предложение: архитектура, стек, сроки, бюджет.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "Пишу код итерациями. Демо каждую неделю, прозрачный прогресс.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Деплой, настройка инфраструктуры, мониторинг, документация.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Частые вопросы",
        items: [
          { q: "Сколько стоит проект?", a: "Зависит от сложности. Лендинг — от $400, корпоративный сайт — от $1200, MVP мобильного приложения — от $2500. Финальную цифру согласуем после брифа." },
          { q: "Как происходит оплата?", a: "Предоплата 30–50%, остаток по этапам или после релиза. Работаю по договору — ИП или самозанятость. SWIFT, криптовалюта, карта — по ситуации." },
          { q: "Какие сроки?", a: "Лендинг — 1–2 недели. Корпоративный сайт — 3–5 недель. MVP мобильного приложения — 6–10 недель. Точный срок называю в техпредложении." },
          { q: "Поддерживаете проект после релиза?", a: "Да. Первый месяц — бесплатно (исправление багов). Дальше — по ставке или через retainer (фиксированные часы в месяц)." },
          { q: "Работаете один или с командой?", a: "Обычно fullstack-проекты веду один. На крупные задачи привлекаю дизайнера, QA или второго разработчика — но координирую всё сам." },
          { q: "Есть ли NDA?", a: "Подпишу без вопросов. Код остаётся у вас, передаю репозиторий и доступы в конце проекта." },
          { q: "На каких языках говорите?", a: "Русский — родной. English — свободно в переписке и созвонах (techical level B2+)." },
          { q: "Что если я не разбираюсь в технологиях?", a: "Это нормально. Объясню человеческим языком, предложу варианты, помогу выбрать. От вас нужна задача и видение — технические решения моя часть." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Привет, я Владислав.",
        body: [
          "Fullstack-разработчик с 2+ годами в продакшене. Делаю сайты, мобильные приложения и интегрирую 3D-модели в веб.",
          "Работаю от идеи до продакшена: проектирую архитектуру, пишу фронт и бэк, настраиваю инфраструктуру и выкатываю.",
          "Люблю задачи, где нужно соединить визуал с инженерией — интерактивные витрины, продуктовые приложения, маркетплейсы с нестандартным UX.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#mobile", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Flutter", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "NestJS", "Express", "Fastify", "Python / FastAPI", "Prisma", "tRPC", "REST", "WebSockets"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "GitHub Actions", "VPS / Linux", "CI/CD"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (для 3D-ассетов)", "Postman", "Sentry"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          name: "Villa Jaconda",
          kind: "Кроссплатформенное приложение",
          year: "2025",
          role: "Fullstack / Lead",
          summary:
            "Мобильное приложение для бронирования загородного дома. Полный цикл: от прототипа до релиза в сторах.",
          features: [
            "Бронирование с живым календарём занятости",
            "Интегрированная платёжная система",
            "Админ-панель: управление акциями, кэшбеком, розыгрышами в реальном времени",
            "Push-уведомления о событиях для гостей",
          ],
          stack: ["React Native", "Expo", "Node.js", "PostgreSQL", "Redis", "Stripe"],
          metrics: [
            { k: "2", v: "платформы (iOS + Android)" },
            { k: "100%", v: "uptime платежей" },
            { k: "<1s", v: "отклик админ-события" },
          ],
        },
        {
          id: "avtotime",
          code: "case_02",
          name: "Avtotime",
          kind: "Соц-сеть + маркетплейс",
          year: "2024",
          role: "Fullstack",
          summary:
            "Социальная платформа для автолюбителей с встроенным маркетплейсом: продажа и покупка авто, услуги сервисов, обучающие курсы.",
          features: [
            "Лента постов и сообществ, система подписок и реакций",
            "Маркетплейс: авто, запчасти, услуги — по категориям",
            "Автокурсы и геймификация (игры, челленджи)",
            "Раздел «помощь на дороге» с геолокацией",
          ],
          stack: ["React", "Next.js", "NestJS", "MongoDB", "Redis", "Docker", "WebSockets"],
          metrics: [
            { k: "6+", v: "крупных модулей" },
            { k: "realtime", v: "чаты и уведомления" },
            { k: "24/7", v: "поддержка помощи" },
          ],
        },
        {
          id: "studio-3d",
          code: "case_03",
          name: "Studio-3D Showcase",
          kind: "Интерактивный сайт-портфолио",
          year: "2024",
          role: "Frontend / 3D",
          summary:
            "Веб-витрина для дизайн-студии с 3D-сценой продукта в браузере. GPU-оптимизация, lazy-load ассетов, адаптив под мобильные.",
          features: [
            "Three.js сцена с драг-контролом и подсветкой",
            "Scroll-triggered камера и анимации",
            "Оптимизация GLTF и текстур под мобильный GPU",
          ],
          stack: ["Next.js", "Three.js", "R3F", "GSAP", "Blender"],
          metrics: [
            { k: "60fps", v: "на mid-range mobile" },
            { k: "-70%", v: "размер ассетов" },
            { k: "A+", v: "Lighthouse" },
          ],
        },
      ],
      timeline: [
        { when: "2026", title: "Fullstack Freelance", org: "Независимые проекты", note: "Villa Jaconda, студийные витрины, MVP для стартапов" },
        { when: "2024–2025", title: "Fullstack Developer", org: "Avtotime", note: "Проектирование и поддержка соц-сети + маркетплейса" },
        { when: "2023–2024", title: "Frontend Developer", org: "Web-студия", note: "Лендинги, интернет-магазины, интеграции оплат" },
        { when: "2023", title: "Старт в разработке", org: "Self-taught → коммерция", note: "React, Node.js, первые клиенты" },
      ],
      contact: {
        cmd: "./contact --send",
        title: "Напишите — отвечу в тот же день",
        body: "Обсудим задачу, сроки и бюджет. Если решим работать — подготовлю техпредложение за 1–2 дня.",
        fields: { name: "как вас зовут", email: "email для ответа", msg: "коротко о задаче" },
        send: "./send",
        success: "[ OK ] сообщение отправлено. скоро свяжусь.",
      },
      footer: "собрано вручную. без шаблонов.",
    },
    en: {
      nav: ["~/home", "~/about", "~/stack", "~/cases", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "I design and ship websites, mobile apps and 3D web scenes. From idea to production — end to end.",
      heroCta: "start a chat",
      heroSecondary: "download short CV",
      status: "AVAILABLE FOR WORK",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ABOUT",
        stack: "02 / STACK",
        cases: "03 / CASES",
        process: "04 / PROCESS",
        timeline: "05 / EXPERIENCE",
        faq: "06 / FAQ",
        contact: "07 / CONTACT",
      },
      marquee: [
        "2+ years in production",
        "fullstack · web · mobile · 3d",
        "idea to deploy",
        "same-day reply",
        "remote-friendly",
        "russian · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "How I work",
        steps: [
          { n: "01", t: "Brief", d: "We scope the task, goals, constraints. I ask the right questions.", tools: "call · text · figma" },
          { n: "02", t: "Spec", d: "I deliver a technical proposal: architecture, stack, timeline, budget.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "I ship iteratively. Weekly demos, transparent progress.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Deploy, infra setup, monitoring, documentation.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Frequently asked",
        items: [
          { q: "How much does a project cost?", a: "Depends on scope. Landing from $400, corporate site from $1200, mobile MVP from $2500. Final number after the brief." },
          { q: "How do payments work?", a: "30–50% upfront, the rest by milestones or on delivery. I work with a contract. SWIFT, crypto, card — whichever works." },
          { q: "What are the timelines?", a: "Landing: 1–2 weeks. Corporate site: 3–5 weeks. Mobile MVP: 6–10 weeks. Exact timeline in the proposal." },
          { q: "Do you support the project after launch?", a: "Yes. First month is free (bug fixes). After that — hourly or via monthly retainer." },
          { q: "Solo or with a team?", a: "I usually run fullstack projects solo. For bigger scope I bring a designer, QA or a second dev — but I coordinate everything." },
          { q: "Will you sign an NDA?", a: "Sure. Code stays yours; I hand over the repo and credentials at the end." },
          { q: "What languages do you speak?", a: "Russian — native. English — fluent in writing and calls (technical B2+)." },
          { q: "What if I'm not technical?", a: "That's fine. I explain things plainly, suggest options, help you choose. You bring the task and vision — I bring the engineering." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Hi, I'm Vladislav.",
        body: [
          "Fullstack developer with 2+ years in production. I build websites, mobile apps and plug 3D models into the web.",
          "I work end-to-end: architecture, frontend, backend, infra, deploy.",
          "I like problems where visuals meet engineering — interactive storefronts, product apps, marketplaces with non-trivial UX.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#mobile", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Flutter", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "NestJS", "Express", "Fastify", "Python / FastAPI", "Prisma", "tRPC", "REST", "WebSockets"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "GitHub Actions", "VPS / Linux", "CI/CD"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (for 3D assets)", "Postman", "Sentry"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          name: "Villa Jaconda",
          kind: "Cross-platform mobile app",
          year: "2025",
          role: "Fullstack / Lead",
          summary:
            "Mobile app for booking a countryside villa. Full cycle: from prototype to store release.",
          features: [
            "Booking flow with live availability calendar",
            "Integrated payment system",
            "Admin panel: manage promos, cashback, giveaways in real time",
            "Push notifications for guest events",
          ],
          stack: ["React Native", "Expo", "Node.js", "PostgreSQL", "Redis", "Stripe"],
          metrics: [
            { k: "2", v: "platforms (iOS + Android)" },
            { k: "100%", v: "payments uptime" },
            { k: "<1s", v: "admin event latency" },
          ],
        },
        {
          id: "avtotime",
          code: "case_02",
          name: "Avtotime",
          kind: "Social network + marketplace",
          year: "2024",
          role: "Fullstack",
          summary:
            "A social platform for car enthusiasts with a built-in marketplace: buy/sell vehicles, services, courses.",
          features: [
            "Posts feed, communities, follows and reactions",
            "Marketplace: cars, parts, services — by category",
            "Driving courses and gamification (games, challenges)",
            "Roadside-help section with geolocation",
          ],
          stack: ["React", "Next.js", "NestJS", "MongoDB", "Redis", "Docker", "WebSockets"],
          metrics: [
            { k: "6+", v: "major modules" },
            { k: "realtime", v: "chat + notifications" },
            { k: "24/7", v: "help section" },
          ],
        },
        {
          id: "studio-3d",
          code: "case_03",
          name: "Studio-3D Showcase",
          kind: "Interactive portfolio site",
          year: "2024",
          role: "Frontend / 3D",
          summary:
            "Web showcase for a design studio with an in-browser 3D product scene. GPU-optimized, lazy-loaded, mobile-friendly.",
          features: [
            "Three.js scene with drag controls and lighting",
            "Scroll-triggered camera and animations",
            "GLTF + texture optimization for mobile GPUs",
          ],
          stack: ["Next.js", "Three.js", "R3F", "GSAP", "Blender"],
          metrics: [
            { k: "60fps", v: "on mid-range mobile" },
            { k: "-70%", v: "asset weight" },
            { k: "A+", v: "Lighthouse" },
          ],
        },
      ],
      timeline: [
        { when: "2026", title: "Fullstack Freelance", org: "Independent projects", note: "Villa Jaconda, studio showcases, startup MVPs" },
        { when: "2024–2025", title: "Fullstack Developer", org: "Avtotime", note: "Architecting and maintaining social + marketplace app" },
        { when: "2023–2024", title: "Frontend Developer", org: "Web studio", note: "Landings, e-commerce, payment integrations" },
        { when: "2023", title: "Dev career start", org: "Self-taught → commercial", note: "React, Node.js, first clients" },
      ],
      contact: {
        cmd: "./contact --send",
        title: "Say hi — I reply same day",
        body: "We'll scope the task, timeline, budget. If we're a fit, I deliver a tech proposal in 1–2 days.",
        fields: { name: "your name", email: "reply email", msg: "brief about the task" },
        send: "./send",
        success: "[ OK ] message sent. I'll get back shortly.",
      },
      footer: "hand-built. no templates.",
    },
  },
};
