// Bilingual content + data

window.PORTFOLIO_CONTENT = {
  profile: {
    name: "VLADISLAV_",
    handle: "@nekopunk44",
    location: "Tiraspol, MD",
    years: "2+",
    telegram: "@van_g0ck",
    whatsapp: "+373 775 148 90",
    github: "https://github.com/nekopunk44",
    email: "vladbredihin4@gmail.com",
  },
  i18n: {
    ru: {
      nav: ["~/home", "~/about", "~/cases", "~/lab", "~/stack", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "Проектирую и собираю сайты, мобильные приложения и 3D⁠-⁠сцены. От идеи до прод-деплоя — в одних руках.",
      heroCta: "начать диалог",
      heroSecondary: "скачать краткое CV",
      status: "СВОБОДЕН ДЛЯ ЗАКАЗОВ",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ОБО МНЕ",
        cases: "02 / КЕЙСЫ",
        lab: "03 / ЛАБОРАТОРИЯ",
        stack: "04 / СТЕК",
        process: "05 / ПРОЦЕСС",
        timeline: "06 / ОПЫТ",
        faq: "07 / FAQ",
        contact: "08 / СВЯЗЬ",
      },
      marquee: [
        "2+ лет в продакшене",
        "fullstack · web · mobile · 3d",
        "node · .net · python",
        "от идеи до deploy",
        "ответ в течение дня",
        "работаю удалённо",
        "русский · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "Как я работаю",
        steps: [
          { n: "01", t: "Brief", d: "Обсуждаем задачу, цели и ограничения. Задаю правильные вопросы.", tools: "call · текст · figma" },
          { n: "02", t: "Spec", d: "Составляю техническое предложение: архитектура, стек, сроки, бюджет.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "Пишу код итерациями. Демо каждую неделю, прозрачный прогресс.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Деплой, настройка инфраструктуры, мониторинг, документация.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Частые вопросы",
        items: [
          { q: "Сколько стоит проект?", a: "Зависит от сложности. Лендинг — от $400, корпоративный сайт — от $1200, MVP мобильного приложения — от $2500. Финальную цифру согласуем после брифа." },
          { q: "Как происходит оплата?", a: "Предоплата 30⁠–⁠50%, остаток по этапам или после релиза. Работаю по договору — ИП или самозанятость. SWIFT, криптовалюта, карта — по ситуации." },
          { q: "Какие сроки?", a: "Лендинг — 1⁠–⁠2 недели. Корпоративный сайт — 3⁠–⁠5 недель. MVP мобильного приложения — 6⁠–⁠10 недель. Точный срок называю в техпредложении." },
          { q: "Поддерживаете проект после релиза?", a: "Да. Первый месяц — бесплатно (исправление багов). Дальше — по ставке или через retainer (фиксированные часы в месяц)." },
          { q: "Работаете один или с командой?", a: "Обычно fullstack⁠-⁠проекты веду один. На крупные задачи привлекаю дизайнера, QA или второго разработчика — но координирую всё сам." },
          { q: "Есть ли NDA?", a: "Подпишу без вопросов. Код остаётся у вас, передаю репозиторий и доступы в конце проекта." },
          { q: "На каких языках говорите?", a: "Русский — родной. English — свободно в переписке и созвонах (technical level B2+)." },
          { q: "Что если я не разбираюсь в технологиях?", a: "Это нормально. Объясню человеческим языком, предложу варианты, помогу выбрать. От вас нужна задача и видение — технические решения моя часть." },
          { q: "Можно посмотреть код ваших проектов?", a: "Да. Часть проектов открыта на GitHub — Avtotime, MomentumX, Aura Scanner и другие лежат в публичных репозиториях. Можно оценить архитектуру, тесты и историю коммитов до начала работы." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Привет, я Владислав.",
        body: [
          "Fullstack⁠-⁠разработчик с 2+ годами в продакшене. Делаю сайты, мобильные приложения и интегрирую 3D⁠-⁠модели в веб.",
          "Работаю от идеи до продакшена: проектирую архитектуру, пишу фронт и бэк, настраиваю инфраструктуру и выкатываю. Бэкенд пишу на Node.js и .NET, обработку данных — на Python, мобильные приложения — на React Native и Flutter.",
          "Люблю задачи, где нужно соединить визуал с инженерией — интерактивные витрины, продуктовые приложения, маркетплейсы с нестандартным UX.",
          "Мне мало, чтобы проект просто работал. Он должен производить впечатление.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#flutter", "#dotnet", "#python", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit", "Vite", "Sass"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Expo Router", "Flutter", "Dart", "EAS Build", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "Express", "NestJS", "Fastify", "ASP.NET Core", "C#", "Python / FastAPI", "Prisma", "Sequelize", "tRPC", "REST", "WebSockets", "Socket.IO"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "PGlite (WASM)", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "Let's Encrypt", "GitHub Actions", "Railway", "Cloudflare Workers", "VPS / Linux", "CI/CD"],
          },
          {
            name: "integrations/",
            items: ["Stripe", "Cloudinary", "Telegram Bot API", "OpenRouter", "Claude API", "Ollama", "Whisper", "JWT / OAuth 2.0", "SMTP / MailKit"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (для 3D⁠-⁠ассетов)", "Postman", "Sentry", "Jest", "ESLint", "Electron", "ffmpeg"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          context: "Свести бронирование, программу лояльности и управление в одно приложение: гость видит актуальную занятость и свои бонусы, владелец — выручку, события и начисления.",
          name: "Villa Jaconda",
          kind: "Кроссплатформенное приложение · бронирование и лояльность",
          role: "Fullstack / Lead",
          summary:
            "Мобильное приложение для сети вилл: бронирование по календарю, программа лояльности с уровнями и админ-панель с финансовой аналитикой. Полный цикл — от прототипа до сборок в сторы.",
          features: [
            "Просмотр и бронирование вилл с выбором дат через календарь",
            "Уровни лояльности Bronze -> Silver -> Gold -> Platinum, графики трат за 6 месяцев",
            "Push⁠-⁠уведомления через Expo и центр уведомлений с фильтрами по типу",
            "Живые обновления без перезагрузки через Server-Sent Events",
            "История бронирований, отзывы 1⁠–⁠5 звёзд, светлая и тёмная темы",
            "Админ-панель: пользователи, пополнение баланса, события, аналитика выручки",
          ],
          stack: ["React Native 0.83", "Expo 55", "React Navigation", "Node.js", "Express", "Sequelize", "PostgreSQL", "JWT", "Railway", "GitHub Actions"],
          metrics: [
            { k: "253", v: "юнит-теста (Jest + supertest)" },
            { k: "2", v: "платформы: iOS + Android через EAS" },
            { k: "4", v: "уровня программы лояльности" },
          ],
          links: {
            live: "https://villajaconda.com",
            liveLabel: "сайт виллы",
            repo: "https://github.com/nekopunk44/Loyalty_app",
          },
        },
        {
          id: "avtotime",
          code: "case_02",
          context: "Автолюбитель ищет машину на одной площадке, общается на другой, готовится к экзамену на третьей. Задача — собрать три сценария в одном продукте так, чтобы не чувствовалась склейка.",
          name: "Avtotime",
          kind: "Монорепо: соцсеть + маркетплейс + обучение",
          role: "Fullstack",
          summary:
            "Социальная платформа для автомобилистов: маркетплейс объявлений, подготовка к экзамену ПДД и общение в реальном времени. Монорепо из четырёх кодовых баз вокруг одного API: веб-соцсеть, отдельный веб-маркет на TypeScript, приложение на Expo и Express⁠-⁠бэкенд. Деплой бэкенда автоматический, из GitHub Actions.",
          features: [
            "Четыре кодовые базы в одном репозитории: Express-API, веб-соцсеть, веб-маркет на 32 тыс. строк и мобильное приложение на Expo с 56 экранами",
            "Маркетплейс: 8 типов объявлений, тарифы free/pro/business, оплата Stripe с идемпотентной активацией по двум каналам — клиентский confirm и webhook с проверкой подписи",
            "Соцсеть: лента, истории, подписки, личные чаты и уведомления на Socket.IO с Redis⁠-⁠адаптером — состояние сокетов общее между репликами",
            "Тренажёр ПДД: 339 вопросов, распарсенных собственным скриптом, режимы экзамена, марафона и практики",
            "AI⁠-⁠модерация в два провайдера: OpenAI omni-moderation либо полностью локальный nsfwjs на TensorFlow.js; очередь с атомарным захватом задач и разбором зависших",
            "Эксплуатация: node:cluster по числу ядер, graceful shutdown, rate limiting на Nginx и в приложении, шифрование чувствительных полей AES-256-GCM",
            "Инфраструктура: docker-compose из 5 сервисов (Mongo, Redis, backend, Nginx, certbot); автодеплой бэкенда из GitHub Actions по push",
          ],
          stack: ["React 19", "Redux Toolkit", "TypeScript", "Vite", "Tailwind 4", "Expo 55 / React Native", "Zustand", "Node.js 20", "Express 5", "MongoDB", "Redis", "Socket.IO", "Stripe", "Cloudinary", "Docker Compose", "Nginx", "GitHub Actions"],
          metrics: [
            { k: "4", v: "кодовые базы: API, соцсеть, маркет, мобильное" },
            { k: "82k", v: "строк исходников в 398 файлах" },
            { k: "150+", v: "HTTP⁠-⁠эндпоинтов, 25 моделей MongoDB" },
            { k: "56", v: "экранов в мобильном приложении" },
          ],
          links: {
            live: "https://avtotime.org",
            repo: "https://github.com/nekopunk44/Avtotime",
          },
        },
        {
          id: "momentumx",
          code: "case_03",
          context: "Агентству нужен сайт, который продаёт сам: показывает уровень работ, считает цену под регион клиента и не теряет ни одной заявки.",
          name: "MomentumX",
          kind: "Сайт digital⁠-⁠агентства · WebGL + .NET",
          role: "Fullstack / 3D",
          summary:
            "Платформа digital⁠-⁠агентства: анимированный WebGL⁠-⁠фронтенд, backend на ASP.NET Core для приёма заявок, региональное ценообразование и задел под AI⁠-⁠аналитику обращений.",
          features: [
            "Hero⁠-⁠сцена на Three.js, скролл-анимации на GSAP и Framer Motion",
            "Калькулятор стоимости с региональными тарифами по геолокации (ipinfo.io)",
            "Приём и хранение заявок, уведомления в Telegram Bot API и на SMTP",
            "Разделы: услуги, портфолио, статистика, команда, игровые серверы",
            "Интеграция OpenRouter AI для анализа входящих обращений",
          ],
          stack: ["Next.js 16", "React 18", "TypeScript", "Tailwind", "Three.js", "GSAP", "Framer Motion", "ASP.NET Core 8", "C#", "MongoDB", "MailKit"],
          metrics: [
            { k: "130", v: "коммитов в основной ветке" },
            { k: "2", v: "рантайма в связке: Node + .NET" },
            { k: "MIT", v: "открытый исходный код" },
          ],
          links: {
            live: "https://momentumx.club",
            repo: "https://github.com/nekopunk44/MomentumX",
          },
        },
        {
          id: "aura-scanner",
          code: "case_04",
          context: "Оцифровать, распознать и подписать документ прямо с телефона — без сканера, без пересылки файлов туда-обратно и без платного SDK для детекции.",
          name: "Aura Scanner",
          kind: "Мобильный сканер документов · Flutter + OpenCV",
          role: "Fullstack / Mobile",
          summary:
            "Самый большой мой проект по объёму кода: Flutter⁠-⁠клиент на 83 тыс. строк Dart и 55 экранов плюс бэкенд на Express/TypeScript с MongoDB. Живая детекция контура документа на OpenCV, локальный OCR, экспорт в PDF/XLSX/PPTX. Тяжёлые вычисления вынесены в изоляты, 260 тестов гоняются в CI на каждый пуш.",
          features: [
            "Живая детекция четырёхугольника документа в потоке кадров камеры: Canny -> контуры -> warpPerspective на OpenCV, сглаживание углов между кадрами, расчёт в изоляте",
            "Своя детекция страницы данных раскрытого паспорта — вместо платного Scanbot SDK, на который нет лицензии: скоринг MRZ⁠-⁠полосы, выбор нужной стороны разворота",
            "OCR на двух движках: Tesseract с офлайн-словарями rus/eng и ML Kit; перевод, определение языка, штрихкоды",
            "Извлечение таблиц из скана в XLSX: разбор HOCR⁠-⁠координат слов и детекция нарисованной сетки по проекциям тёмных пикселей",
            "Экспорт в PDF, XLSX и PPTX — PPTX собирается вручную как Office Open XML в ZIP⁠-⁠контейнере",
            "Бэкенд: сессии на JWT с ротацией и single-flight обновлением токена, пять OAuth⁠-⁠провайдеров, обмен одноразового кода вместо токена в redirect-URL",
          ],
          stack: ["Flutter", "Dart 3.9", "OpenCV (dartcv)", "ML Kit", "Tesseract", "Express 4", "TypeScript strict", "MongoDB / Mongoose", "JWT + OAuth 2.0", "Sentry", "Railway", "GitHub Actions"],
          metrics: [
            { k: "83k", v: "строк Dart в клиенте: 133 файла, 55 экранов" },
            { k: "260", v: "тестов Flutter, прогон в CI на каждый пуш" },
            { k: "38", v: "HTTP⁠-⁠обработчиков бэкенда, 5 моделей MongoDB" },
            { k: "1042", v: "ключа локализации — паритет ru/en" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Aura-scaner",
          },
        },
        {
          id: "quant",
          code: "case_05",
          context: "Торговая идея всегда звучит убедительно. Задача — отличать настоящее преимущество от совпадения статистикой, а не на глаз.",
          name: "AI-Quant Insights",
          kind: "Исследовательская система · данные + LLM",
          role: "Fullstack / Data",
          summary:
            "Research⁠-⁠инструмент: превращает торговые гипотезы в проверяемые эксперименты и выносит статистический вердикт — настоящее преимущество или красивый нарратив. Вся статистика против переобучения написана с нуля на TypeScript: у вычислительного ядра ноль рантайм-зависимостей.",
          features: [
            "Статистика против переобучения — своя реализация, без numpy и внешних библиотек: Deflated и Probabilistic Sharpe, PBO через CSCV с перебором разбиений, purged K-fold с embargo, normCdf/normInv",
            "Walk-forward: параметры подбираются на train⁠-⁠окне, победитель оценивается на нетронутом test⁠-⁠окне, эквити между фолдами сшивается компаундингом",
            "Вердикт обязательно проходит стресс по издержкам 1x/2x/5x: прошёл статистику, но провалил трение — метка понижается до weak",
            "JSON-DSL для гипотез: LLM отдаёт дерево условий, компилятор валидирует его рекурсивно и указывает адрес ошибки (entry.and[1].left)",
            "Одна схема БД на двух движках: сетевой PostgreSQL и PostgreSQL в WASM (PGlite) для десктопной сборки — интерфейс запросов одинаковый",
            "Клиенты тонкие, вся математика на сервере: React⁠-⁠дашборд на 14 страниц, Electron, Telegram⁠-⁠бот, Expo",
            "История коммитов фиксирует и отрицательные результаты: целые пачки гипотез отклонены на отложенной выборке",
          ],
          stack: ["TypeScript 5.9", "Node.js 22", "Express 5", "drizzle-orm", "PostgreSQL", "PGlite (WASM)", "React 19", "Vite", "Tailwind 4", "Python 3.13 / FastAPI", "Electron", "Expo", "Anthropic SDK", "Ollama"],
          metrics: [
            { k: "0", v: "рантайм-зависимостей у ядра бэктеста (25 модулей)" },
            { k: "66", v: "HTTP⁠-⁠обработчиков API, 23 таблицы в схеме" },
            { k: "170+", v: "проверок в assert⁠-⁠скриптах, без тест-фреймворка" },
            { k: "4", v: "клиента поверх одного ядра" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Quant",
          },
        },
        {
          id: "voice",
          code: "case_06",
          context: "Голосовой помощник, который не отправляет речь и команды в облако: распознавание и модель работают на своём железе, а команда выполняется на том устройстве, где она нужна.",
          name: "Enard",
          kind: "Голосовой ассистент · локальная LLM",
          role: "Fullstack / Desktop + Mobile",
          summary:
            "Кроссплатформенный ассистент с локальной LLM (Ollama, qwen2.5:3b) и локальным распознаванием речи (whisper.cpp). Node/Express⁠-⁠хаб маршрутизирует команды между устройствами по WebSocket; клиентов три — Electron под Windows, приложение на Expo и PWA. Проект в активной разработке, тестов и CI пока нет. Репозиторий приватный: код показываю по запросу.",
          features: [
            "Локальный контур целиком: whisper.cpp для речи, Ollama/qwen2.5:3b для модели, Piper для озвучки; облако подключается только как фолбэк",
            "Маршрутизация команд между устройствами: WebSocket-RPC с корреляцией по requestId, таймаутом 10 с, heartbeat и переподключением клиента с экспоненциальной задержкой",
            "Целевое устройство выбирает сама модель: системный промпт собирается из реестра устройств — платформа, статус онлайн, возможности каждого",
            "Сопряжение по одноразовому 6⁠-⁠значному коду с TTL 5 минут и QR со списком LAN⁠-⁠адресов; на диске хранится только sha256 токена",
            "Произвольные PowerShell⁠-⁠команды — только через двухфазное подтверждение и deny-list (rm -Recurse, format, diskpart, shutdown)",
            "10 инструментов для модели: время, открыть URL/приложение/файл, веб-поиск, заметки, поиск файлов, отправка в Telegram через MTProto",
            "Работа без интернета: если модель недоступна, команды разбираются регулярками, а ошибка объясняется человеческим языком",
          ],
          stack: ["Node.js 20", "Express 4", "ws (WebSocket)", "Ollama / qwen2.5:3b", "whisper.cpp", "Piper TTS", "ffmpeg", "Electron 43", "Expo 55 / React Native", "PWA + Service Worker", "OpenAI SDK"],
          metrics: [
            { k: "3", v: "клиента на одном REST+WS⁠-⁠протоколе" },
            { k: "10", v: "LLM⁠-⁠инструментов, 11 эндпоинтов + WebSocket⁠-⁠хаб" },
            { k: "6k", v: "строк своего кода в 35 файлах" },
          ],
        },
      ],
      lab: {
        cmd: "ls ~/lab --experimental",
        title: "Лаборатория",
        note: "Пет-проекты и прототипы: пробую технологии, которые потом уходят в клиентские задачи. Весь код открыт.",
        items: [
          {
            name: "Завод нарезок",
            lang: "Python",
            kind: "Пайплайн обработки видео",
            desc: "Полуавтоматический конвейер: анализирует VOD стримов по активности чата, качает только нужные фрагменты, транскрибирует и собирает вертикальные клипы 1080×1920 с субтитрами. Веб-редактор для ревью и автопостинг в YouTube и TikTok.",
            tags: ["Python", "ffmpeg", "faster-whisper", "Claude / Gemini / Ollama", "Expo"],
            repo: "https://github.com/nekopunk44/narezka",
          },
          {
            name: "ZenPulse",
            lang: "TypeScript",
            kind: "Прототип мобильного приложения",
            desc: "Приложение для медитаций на Expo Router: paywall с месячной и годовой подпиской, библиотека сессий, таймер с дыхательными паттернами и фоновым звуком, ежедневный AI⁠-⁠текст «Vibe of the day».",
            tags: ["Expo", "React Native", "TypeScript", "Expo Router", "AsyncStorage"],
            repo: "https://github.com/nekopunk44/ZenPulse-AI-Meditation-App-Prototype",
          },
          {
            name: "Mythory",
            lang: "JavaScript",
            kind: "Платформа веб-новелл · в разработке",
            desc: "Читатель и автор в одном продукте: чтение по главам, закладки, свои истории и редактор. Макет проработан на 35 экранов в трёх ширинах — десктоп, планшет, мобильный — с отдельными состояниями под бесплатный тариф. Свёрстана витрина: герой-блок, каталог жанров, шапка с поиском и меню пользователя, подвал. Дальше — читалка, редактор глав и личный кабинет.",
            tags: ["React 19", "Vite", "Sass", "Figma"],
            repo: "https://github.com/nekopunk44/Mythory",
          },
        ],
        more: "весь код на github",
      },
      timeline: [
        {
          when: "2026",
          title: "Fullstack Freelance",
          org: "Независимые проекты",
          summary: "Веду проекты целиком: бриф, архитектура, код, инфраструктура, поддержка.",
          items: [
            "MomentumX — платформа digital⁠-⁠агентства: WebGL⁠-⁠фронтенд на Next.js 16 и backend на ASP.NET Core 8, калькулятор с региональными тарифами, приём заявок в Telegram и на SMTP",
            "Aura Scanner — Flutter⁠-⁠сканер документов на 83 тыс. строк Dart: детекция контура на OpenCV в потоке кадров, OCR на двух движках, экспорт в PDF/XLSX/PPTX, 260 тестов в CI",
            "AI-Quant Insights — исследовательская система: статистика против переобучения написана с нуля на TypeScript, четыре клиента поверх общего ядра",
            "Enard — голосовой ассистент с локальной LLM и whisper.cpp: хаб на Node маршрутизирует команды между Electron, Expo и PWA по WebSocket",
          ],
          stack: ["Next.js", "ASP.NET Core", "Flutter", "OpenCV", "Python", "Electron", "Docker"],
        },
        {
          when: "2025–2026",
          title: "Fullstack / Lead",
          org: "Villa Jaconda",
          summary: "Мобильное приложение сети вилл — полный цикл от прототипа до сборок в сторы.",
          items: [
            "Бронирование по календарю занятости и программа лояльности с четырьмя уровнями",
            "Админ-панель с финансовой аналитикой, живые обновления через Server-Sent Events",
            "253 юнит-теста, CI/CD на GitHub Actions, сборки под iOS и Android через EAS",
          ],
          stack: ["React Native", "Expo", "Express", "PostgreSQL", "Sequelize", "Railway"],
        },
        {
          when: "2024–2025",
          title: "Fullstack Developer",
          org: "Avtotime",
          summary: "Соцсеть, маркетплейс и подготовка к ПДД вокруг одного API — четыре кодовые базы в монорепо.",
          items: [
            "Маркетплейс объявлений с оплатой через Stripe и обработкой медиа через Cloudinary",
            "Реалтайм-чат и уведомления на Socket.IO с Redis⁠-⁠адаптером, AI⁠-⁠модерация в два провайдера",
            "Мобильное приложение на Expo: 56 экранов поверх того же бэкенда",
            "Инфраструктура: docker-compose из 5 сервисов, Nginx с TLS, автодеплой бэкенда из GitHub Actions",
          ],
          stack: ["React 19", "Redux Toolkit", "Expo", "Express 5", "MongoDB", "Redis", "Socket.IO"],
        },
        {
          when: "2023–2024",
          title: "Frontend Developer",
          org: "Web⁠-⁠студия",
          summary: "Коммерческая разработка на потоке: сайты под ключ и интеграции.",
          items: [
            "Лендинги и корпоративные сайты с нуля по макетам Figma",
            "Интернет-магазины: каталог, корзина, подключение платёжных систем",
          ],
          stack: ["React", "JavaScript", "Sass", "REST"],
        },
        {
          when: "2023",
          title: "Старт в разработке",
          org: "Self-taught -> коммерция",
          summary: "От первых учебных проектов до первых оплаченных заказов.",
          items: [
            "React и Node.js, вёрстка, работа с API",
            "Первые клиенты и первый прод",
          ],
          stack: ["React", "Node.js", "Git"],
        },
      ],
      contact: {
        cmd: "./contact --list",
        title: "Напишите — отвечу в тот же день",
        body: "Обсудим задачу, сроки и бюджет. Если решим работать — подготовлю техпредложение за 1⁠–⁠2 дня.",
        channels: {
          telegram: "быстрее всего",
          whatsapp: "если удобнее",
          email: "для подробных задач",
          github: "код и проекты",
        },
      },
      footer: "собрано вручную. без шаблонов.",
    },
    en: {
      nav: ["~/home", "~/about", "~/cases", "~/lab", "~/stack", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "I design and ship websites, mobile apps and 3D web scenes. From idea to production — end to end.",
      heroCta: "start a chat",
      heroSecondary: "download short CV",
      status: "AVAILABLE FOR WORK",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ABOUT",
        cases: "02 / CASES",
        lab: "03 / LAB",
        stack: "04 / STACK",
        process: "05 / PROCESS",
        timeline: "06 / EXPERIENCE",
        faq: "07 / FAQ",
        contact: "08 / CONTACT",
      },
      marquee: [
        "2+ years in production",
        "fullstack · web · mobile · 3d",
        "node · .net · python",
        "idea to deploy",
        "same-day reply",
        "remote-friendly",
        "russian · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "How I work",
        steps: [
          { n: "01", t: "Brief", d: "We scope the task, goals, constraints. I ask the right questions.", tools: "call · text · figma" },
          { n: "02", t: "Spec", d: "I deliver a technical proposal: architecture, stack, timeline, budget.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "I ship iteratively. Weekly demos, transparent progress.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Deploy, infra setup, monitoring, documentation.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Frequently asked",
        items: [
          { q: "How much does a project cost?", a: "Depends on scope. Landing from $400, corporate site from $1200, mobile MVP from $2500. Final number after the brief." },
          { q: "How do payments work?", a: "30–50% upfront, the rest by milestones or on delivery. I work with a contract. SWIFT, crypto, card — whichever works." },
          { q: "What are the timelines?", a: "Landing: 1–2 weeks. Corporate site: 3–5 weeks. Mobile MVP: 6–10 weeks. Exact timeline in the proposal." },
          { q: "Do you support the project after launch?", a: "Yes. First month is free (bug fixes). After that — hourly or via monthly retainer." },
          { q: "Solo or with a team?", a: "I usually run fullstack projects solo. For bigger scope I bring a designer, QA or a second dev — but I coordinate everything." },
          { q: "Will you sign an NDA?", a: "Sure. Code stays yours; I hand over the repo and credentials at the end." },
          { q: "What languages do you speak?", a: "Russian — native. English — fluent in writing and calls (technical B2+)." },
          { q: "What if I'm not technical?", a: "That's fine. I explain things plainly, suggest options, help you choose. You bring the task and vision — I bring the engineering." },
          { q: "Can I look at your code?", a: "Yes. A good part of my work is open on GitHub — Avtotime, MomentumX, Aura Scanner and others live in public repos. You can judge the architecture, tests and commit history before we start." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Hi, I'm Vladislav.",
        body: [
          "Fullstack developer with 2+ years in production. I build websites, mobile apps and plug 3D models into the web.",
          "I work end-to-end: architecture, frontend, backend, infra, deploy. Backends on Node.js and .NET, data pipelines in Python, mobile on React Native and Flutter.",
          "I like problems where visuals meet engineering — interactive storefronts, product apps, marketplaces with non-trivial UX.",
          "I don't want projects to just work. I want them to leave an impression.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#flutter", "#dotnet", "#python", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit", "Vite", "Sass"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Expo Router", "Flutter", "Dart", "EAS Build", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "Express", "NestJS", "Fastify", "ASP.NET Core", "C#", "Python / FastAPI", "Prisma", "Sequelize", "tRPC", "REST", "WebSockets", "Socket.IO"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "PGlite (WASM)", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "Let's Encrypt", "GitHub Actions", "Railway", "Cloudflare Workers", "VPS / Linux", "CI/CD"],
          },
          {
            name: "integrations/",
            items: ["Stripe", "Cloudinary", "Telegram Bot API", "OpenRouter", "Claude API", "Ollama", "Whisper", "JWT / OAuth 2.0", "SMTP / MailKit"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (for 3D assets)", "Postman", "Sentry", "Jest", "ESLint", "Electron", "ffmpeg"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          context: "Fold booking, the loyalty programme and back-office into one app: the guest sees real availability and their own points, the owner sees revenue, events and payouts.",
          name: "Villa Jaconda",
          kind: "Cross-platform app · booking and loyalty",
          role: "Fullstack / Lead",
          summary:
            "Mobile app for a villa network: calendar booking, a tiered loyalty program and an admin dashboard with financial analytics. Full cycle — from prototype to store builds.",
          features: [
            "Villa browsing and booking with calendar date selection",
            "Loyalty tiers Bronze → Silver → Gold → Platinum, 6-month spending charts",
            "Expo push notifications and a notification center filtered by type",
            "Live updates without reload via Server-Sent Events",
            "Booking history, 1–5★ reviews, light and dark themes",
            "Admin panel: users, balance top-ups, events, revenue analytics",
          ],
          stack: ["React Native 0.83", "Expo 55", "React Navigation", "Node.js", "Express", "Sequelize", "PostgreSQL", "JWT", "Railway", "GitHub Actions"],
          metrics: [
            { k: "253", v: "unit tests (Jest + supertest)" },
            { k: "2", v: "platforms: iOS + Android via EAS" },
            { k: "4", v: "loyalty tiers" },
          ],
          links: {
            live: "https://villajaconda.com",
            liveLabel: "villa website",
            repo: "https://github.com/nekopunk44/Loyalty_app",
          },
        },
        {
          id: "avtotime",
          code: "case_02",
          context: "A driver shops for a car on one site, talks on another, revises for the exam on a third. The task was to fold all three into one product without it feeling stitched together.",
          name: "Avtotime",
          kind: "Monorepo: social network + marketplace + learning",
          role: "Fullstack",
          summary:
            "A social platform for drivers: a classifieds marketplace, driving-exam prep and real-time communication. A monorepo of four codebases around one API: the social web app, a separate TypeScript market web app, an Expo mobile app and the Express backend. Backend deploys automatically from GitHub Actions.",
          features: [
            "Four codebases in one repository: the Express API, the social web app, a 32k-line market web app and an Expo mobile app with 56 screens",
            "Marketplace: 8 listing types, free/pro/business plans, Stripe payments activated idempotently through two channels — client confirm and a signature-verified webhook",
            "Social layer: feed, stories, follows, direct chats and notifications on Socket.IO with a Redis adapter — socket state is shared across replicas",
            "Exam prep: 339 questions parsed by a custom script, exam / marathon / practice modes",
            "AI moderation with two providers: OpenAI omni-moderation or a fully local nsfwjs on TensorFlow.js; a queue with atomic task claiming and stuck-job recovery",
            "Operations: node:cluster across cores, graceful shutdown, rate limiting in Nginx and in the app, AES-256-GCM encryption of sensitive fields",
            "Infrastructure: a 5-service docker-compose (Mongo, Redis, backend, Nginx, certbot); backend auto-deploy from GitHub Actions on push",
          ],
          stack: ["React 19", "Redux Toolkit", "TypeScript", "Vite", "Tailwind 4", "Expo 55 / React Native", "Zustand", "Node.js 20", "Express 5", "MongoDB", "Redis", "Socket.IO", "Stripe", "Cloudinary", "Docker Compose", "Nginx", "GitHub Actions"],
          metrics: [
            { k: "4", v: "codebases: API, social, market, mobile" },
            { k: "82k", v: "lines of source across 398 files" },
            { k: "150+", v: "HTTP endpoints, 25 MongoDB models" },
            { k: "56", v: "screens in the mobile app" },
          ],
          links: {
            live: "https://avtotime.org",
            repo: "https://github.com/nekopunk44/Avtotime",
          },
        },
        {
          id: "momentumx",
          code: "case_03",
          context: "An agency needs a site that sells on its own: it has to show the standard of the work, price by the visitor’s region and never drop an enquiry.",
          name: "MomentumX",
          kind: "Digital agency site · WebGL + .NET",
          role: "Fullstack / 3D",
          summary:
            "A digital agency platform: animated WebGL frontend, an ASP.NET Core backend for lead capture, regional pricing logic and a foundation for AI-driven lead analysis.",
          features: [
            "Three.js hero scene, scroll animations on GSAP and Framer Motion",
            "Pricing calculator with location-based regional tariffs (ipinfo.io)",
            "Lead capture and storage, notifications via Telegram Bot API and SMTP",
            "Sections: services, portfolio, stats, team, game servers",
            "OpenRouter AI integration for analyzing incoming requests",
          ],
          stack: ["Next.js 16", "React 18", "TypeScript", "Tailwind", "Three.js", "GSAP", "Framer Motion", "ASP.NET Core 8", "C#", "MongoDB", "MailKit"],
          metrics: [
            { k: "130", v: "commits on the main branch" },
            { k: "2", v: "runtimes together: Node + .NET" },
            { k: "MIT", v: "open source" },
          ],
          links: {
            live: "https://momentumx.club",
            repo: "https://github.com/nekopunk44/MomentumX",
          },
        },
        {
          id: "aura-scanner",
          code: "case_04",
          context: "Capture, recognise and sign a document straight from the phone — no scanner, no mailing files back and forth, no paid SDK for detection.",
          name: "Aura Scanner",
          kind: "Mobile document scanner · Flutter + OpenCV",
          role: "Fullstack / Mobile",
          summary:
            "My largest project by code volume: a Flutter client of 83k lines of Dart across 55 screens plus an Express/TypeScript backend on MongoDB. Live document edge detection on OpenCV, on-device OCR, export to PDF/XLSX/PPTX. Heavy work runs in isolates; 260 tests run in CI on every push.",
          features: [
            "Live document quad detection in the camera frame stream: Canny → contours → warpPerspective on OpenCV, corner smoothing across frames, computed in an isolate",
            "Own detection of the passport data page instead of the paid Scanbot SDK (no licence for it): MRZ band scoring, picking the right side of the spread",
            "OCR on two engines: Tesseract with offline rus/eng data and ML Kit; translation, language ID, barcodes",
            "Table extraction from a scan into XLSX: parsing HOCR word coordinates and detecting drawn grid lines by dark-pixel projections",
            "Export to PDF, XLSX and PPTX — the PPTX is assembled by hand as Office Open XML inside a ZIP",
            "Backend: JWT sessions with rotation and single-flight token refresh, five OAuth providers, a one-time code exchange instead of a token in the redirect URL",
          ],
          stack: ["Flutter", "Dart 3.9", "OpenCV (dartcv)", "ML Kit", "Tesseract", "Express 4", "TypeScript strict", "MongoDB / Mongoose", "JWT + OAuth 2.0", "Sentry", "Railway", "GitHub Actions"],
          metrics: [
            { k: "83k", v: "lines of Dart in the client: 133 files, 55 screens" },
            { k: "260", v: "Flutter tests, run in CI on every push" },
            { k: "38", v: "backend HTTP handlers, 5 MongoDB models" },
            { k: "1042", v: "localization keys — full ru/en parity" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Aura-scaner",
          },
        },
        {
          id: "quant",
          code: "case_05",
          context: "A trading idea always sounds convincing. The task is to tell a real edge from a coincidence with statistics rather than by eye.",
          name: "AI-Quant Insights",
          kind: "Research system · data + LLM",
          role: "Fullstack / Data",
          summary:
            "A research instrument: it turns trading hypotheses into testable experiments and returns a statistical verdict — a real edge or a compelling narrative. All the anti-overfitting statistics are written from scratch in TypeScript; the compute core has zero runtime dependencies.",
          features: [
            "Anti-overfitting statistics implemented from scratch, no numpy, no external libraries: Deflated and Probabilistic Sharpe, PBO via CSCV over enumerated splits, purged K-fold with embargo, normCdf/normInv",
            "Walk-forward: parameters are fitted on the train window, the winner is scored on an untouched test window, equity is compounded across folds",
            "Every verdict is stress-tested at 1x/2x/5x costs: passing the statistics but failing friction downgrades the label to weak",
            "A JSON DSL for hypotheses: the LLM returns a condition tree, the compiler validates it recursively and reports the path of the error (entry.and[1].left)",
            "One DB schema on two engines: networked PostgreSQL and PostgreSQL in WASM (PGlite) for the desktop build — identical query interface",
            "Thin clients, all math on the server: a 14-page React dashboard, Electron, a Telegram bot, Expo",
            "The commit history also records negative results: whole batches of hypotheses rejected on the holdout",
          ],
          stack: ["TypeScript 5.9", "Node.js 22", "Express 5", "drizzle-orm", "PostgreSQL", "PGlite (WASM)", "React 19", "Vite", "Tailwind 4", "Python 3.13 / FastAPI", "Electron", "Expo", "Anthropic SDK", "Ollama"],
          metrics: [
            { k: "0", v: "runtime deps in the backtest core (25 modules)" },
            { k: "66", v: "API HTTP handlers, 23 tables in the schema" },
            { k: "170+", v: "assertions in custom scripts, no test framework" },
            { k: "4", v: "clients on a single core" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Quant",
          },
        },
        {
          id: "voice",
          code: "case_06",
          context: "A voice assistant that never ships speech or commands to the cloud: recognition and the model run on your own hardware, and the command executes on the device where it is actually needed.",
          name: "Enard",
          kind: "Voice assistant · local LLM",
          role: "Fullstack / Desktop + Mobile",
          summary:
            "A cross-platform assistant with a local LLM (Ollama, qwen2.5:3b) and local speech recognition (whisper.cpp). A Node/Express hub routes commands between devices over WebSocket; three clients — Electron on Windows, an Expo app and a PWA. Actively in development, no tests or CI yet. The repository is private: I can walk through the code on request.",
          features: [
            "Fully local loop: whisper.cpp for speech, Ollama/qwen2.5:3b for the model, Piper for speech output; the cloud is only a fallback",
            "Command routing between devices: WebSocket RPC correlated by requestId, a 10s timeout, heartbeats and client reconnect with exponential backoff",
            "The model picks the target device itself: the system prompt is assembled from the device registry — platform, online status and capabilities of each",
            "Pairing via a one-time 6-digit code with a 5-minute TTL and a QR listing LAN addresses; only the sha256 of the token is stored on disk",
            "Arbitrary PowerShell commands run only behind two-phase confirmation and a deny-list (recursive delete, format, diskpart, shutdown)",
            "10 tools for the model: time, open URL/app/file, web search, notes, file search, sending files to Telegram over MTProto",
            "Works offline: when the model is unavailable, commands are parsed with regexes and errors are explained in plain language",
          ],
          stack: ["Node.js 20", "Express 4", "ws (WebSocket)", "Ollama / qwen2.5:3b", "whisper.cpp", "Piper TTS", "ffmpeg", "Electron 43", "Expo 55 / React Native", "PWA + Service Worker", "OpenAI SDK"],
          metrics: [
            { k: "3", v: "clients on one REST+WS protocol" },
            { k: "10", v: "LLM tools, 11 endpoints + a WebSocket hub" },
            { k: "6k", v: "lines of own code across 35 files" },
          ],
        },
      ],
      lab: {
        cmd: "ls ~/lab --experimental",
        title: "Lab",
        note: "Pet projects and prototypes: I try technologies here before they land in client work. All code is open.",
        items: [
          {
            name: "Clip Factory",
            lang: "Python",
            kind: "Video processing pipeline",
            desc: "A semi-automatic pipeline: it analyzes stream VODs by chat intensity, downloads only the parts that matter, transcribes them and assembles vertical 1080×1920 clips with subtitles. Local web editor for review plus auto-publishing to YouTube and TikTok.",
            tags: ["Python", "ffmpeg", "faster-whisper", "Claude / Gemini / Ollama", "Expo"],
            repo: "https://github.com/nekopunk44/narezka",
          },
          {
            name: "ZenPulse",
            lang: "TypeScript",
            kind: "Mobile app prototype",
            desc: "A meditation app on Expo Router: paywall with monthly and yearly plans, session library, timer with breathing patterns and background audio, plus a daily AI-generated \"Vibe of the day\".",
            tags: ["Expo", "React Native", "TypeScript", "Expo Router", "AsyncStorage"],
            repo: "https://github.com/nekopunk44/ZenPulse-AI-Meditation-App-Prototype",
          },
          {
            name: "Mythory",
            lang: "JavaScript",
            kind: "Web-novel platform · in progress",
            desc: "Reader and author in one product: chapter-by-chapter reading, bookmarks, your own stories and an editor. The design covers 35 screens across three widths — desktop, tablet, mobile — with separate states for the free tier. The storefront is built: hero, genre catalog, header with search and user menu, footer. Next up: the reader, the chapter editor and the dashboard.",
            tags: ["React 19", "Vite", "Sass", "Figma"],
            repo: "https://github.com/nekopunk44/Mythory",
          },
        ],
        more: "all code on github",
      },
      timeline: [
        {
          when: "2026",
          title: "Fullstack Freelance",
          org: "Independent projects",
          summary: "I run projects end to end: brief, architecture, code, infra, support.",
          items: [
            "MomentumX — digital agency platform: WebGL frontend on Next.js 16 with an ASP.NET Core 8 backend, regional pricing calculator, leads to Telegram and SMTP",
            "Aura Scanner — 83k-line Flutter document scanner: OpenCV edge detection in the camera stream, OCR on two engines, export to PDF/XLSX/PPTX, 260 tests in CI",
            "AI-Quant Insights — research system: anti-overfitting statistics written from scratch in TypeScript, four clients on a shared core",
            "Enard — voice assistant with a local LLM and whisper.cpp: a Node hub routes commands between Electron, Expo and PWA over WebSocket",
          ],
          stack: ["Next.js", "ASP.NET Core", "Flutter", "OpenCV", "Python", "Electron", "Docker"],
        },
        {
          when: "2025–2026",
          title: "Fullstack / Lead",
          org: "Villa Jaconda",
          summary: "Mobile app for a villa network — full cycle from prototype to store builds.",
          items: [
            "Calendar-based booking and a four-tier loyalty program",
            "Admin dashboard with financial analytics, live updates over Server-Sent Events",
            "253 unit tests, CI/CD on GitHub Actions, iOS and Android builds via EAS",
          ],
          stack: ["React Native", "Expo", "Express", "PostgreSQL", "Sequelize", "Railway"],
        },
        {
          when: "2024–2025",
          title: "Fullstack Developer",
          org: "Avtotime",
          summary: "A social network, a marketplace and exam prep around one API — four codebases in a monorepo.",
          items: [
            "Classifieds marketplace with Stripe payments and Cloudinary media processing",
            "Real-time chat and notifications on Socket.IO with a Redis adapter, AI moderation with two providers",
            "Expo mobile app: 56 screens on top of the same backend",
            "Infrastructure: a 5-service docker-compose, Nginx with TLS, backend auto-deploy from GitHub Actions",
          ],
          stack: ["React 19", "Redux Toolkit", "Expo", "Express 5", "MongoDB", "Redis", "Socket.IO"],
        },
        {
          when: "2023–2024",
          title: "Frontend Developer",
          org: "Web studio",
          summary: "Commercial delivery at pace: sites built to spec, plus integrations.",
          items: [
            "Landings and corporate sites built from Figma designs",
            "E-commerce: catalogue, cart, payment provider integrations",
          ],
          stack: ["React", "JavaScript", "Sass", "REST"],
        },
        {
          when: "2023",
          title: "Dev career start",
          org: "Self-taught → commercial",
          summary: "From first practice projects to first paid work.",
          items: [
            "React and Node.js, markup, working with APIs",
            "First clients and first production deploy",
          ],
          stack: ["React", "Node.js", "Git"],
        },
      ],
      contact: {
        cmd: "./contact --list",
        title: "Say hi — I reply same day",
        body: "We'll scope the task, timeline, budget. If we're a fit, I deliver a tech proposal in 1–2 days.",
        channels: {
          telegram: "fastest",
          whatsapp: "if you prefer",
          email: "for detailed briefs",
          github: "code and projects",
        },
      },
      footer: "hand-built. no templates.",
    },
  },
};
