// Bilingual content + data

window.PORTFOLIO_CONTENT = {
  profile: {
    name: "VLADISLAV_",
    handle: "@nekopunk44",
    location: "Tiraspol, MD",
    years: "2+",
    telegram: "@van_g0ck",
    whatsapp: "+373 775 148 90",
    github: "https://github.com/nekopunk44",
    email: "vladbredihin4@gmail.com",
  },
  i18n: {
    ru: {
      nav: ["~/home", "~/about", "~/cases", "~/lab", "~/stack", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "Проектирую и собираю сайты, мобильные приложения и 3D-сцены. От идеи до прод-деплоя — в одних руках.",
      heroCta: "начать диалог",
      heroSecondary: "скачать краткое CV",
      status: "СВОБОДЕН ДЛЯ ЗАКАЗОВ",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ОБО МНЕ",
        cases: "02 / КЕЙСЫ",
        lab: "03 / ЛАБОРАТОРИЯ",
        stack: "04 / СТЕК",
        process: "05 / ПРОЦЕСС",
        timeline: "06 / ОПЫТ",
        faq: "07 / FAQ",
        contact: "08 / СВЯЗЬ",
      },
      marquee: [
        "2+ лет в продакшене",
        "fullstack · web · mobile · 3d",
        "node · .net · python",
        "от идеи до deploy",
        "ответ в течение дня",
        "работаю удалённо",
        "русский · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "Как я работаю",
        steps: [
          { n: "01", t: "Brief", d: "Обсуждаем задачу, цели и ограничения. Задаю правильные вопросы.", tools: "call · текст · figma" },
          { n: "02", t: "Spec", d: "Составляю техническое предложение: архитектура, стек, сроки, бюджет.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "Пишу код итерациями. Демо каждую неделю, прозрачный прогресс.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Деплой, настройка инфраструктуры, мониторинг, документация.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Частые вопросы",
        items: [
          { q: "Сколько стоит проект?", a: "Зависит от сложности. Лендинг — от $400, корпоративный сайт — от $1200, MVP мобильного приложения — от $2500. Финальную цифру согласуем после брифа." },
          { q: "Как происходит оплата?", a: "Предоплата 30–50%, остаток по этапам или после релиза. Работаю по договору — ИП или самозанятость. SWIFT, криптовалюта, карта — по ситуации." },
          { q: "Какие сроки?", a: "Лендинг — 1–2 недели. Корпоративный сайт — 3–5 недель. MVP мобильного приложения — 6–10 недель. Точный срок называю в техпредложении." },
          { q: "Поддерживаете проект после релиза?", a: "Да. Первый месяц — бесплатно (исправление багов). Дальше — по ставке или через retainer (фиксированные часы в месяц)." },
          { q: "Работаете один или с командой?", a: "Обычно fullstack-проекты веду один. На крупные задачи привлекаю дизайнера, QA или второго разработчика — но координирую всё сам." },
          { q: "Есть ли NDA?", a: "Подпишу без вопросов. Код остаётся у вас, передаю репозиторий и доступы в конце проекта." },
          { q: "На каких языках говорите?", a: "Русский — родной. English — свободно в переписке и созвонах (techical level B2+)." },
          { q: "Что если я не разбираюсь в технологиях?", a: "Это нормально. Объясню человеческим языком, предложу варианты, помогу выбрать. От вас нужна задача и видение — технические решения моя часть." },
          { q: "Можно посмотреть код ваших проектов?", a: "Да. Часть проектов открыта на GitHub — Avtotime, MomentumX, Aura Scanner и другие лежат в публичных репозиториях. Можно оценить архитектуру, тесты и историю коммитов до начала работы." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Привет, я Владислав.",
        body: [
          "Fullstack-разработчик с 2+ годами в продакшене. Делаю сайты, мобильные приложения и интегрирую 3D-модели в веб.",
          "Работаю от идеи до продакшена: проектирую архитектуру, пишу фронт и бэк, настраиваю инфраструктуру и выкатываю. Бэкенд пишу на Node.js и .NET, обработку данных — на Python, мобильные приложения — на React Native и Flutter.",
          "Люблю задачи, где нужно соединить визуал с инженерией — интерактивные витрины, продуктовые приложения, маркетплейсы с нестандартным UX.",
          "Мне мало, чтобы проект просто работал. Он должен производить впечатление.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#flutter", "#dotnet", "#python", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit", "Vite", "Sass"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Expo Router", "Flutter", "Dart", "EAS Build", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "Express", "NestJS", "Fastify", "ASP.NET Core", "C#", "Python / FastAPI", "Prisma", "Sequelize", "tRPC", "REST", "WebSockets", "Socket.IO"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "TimescaleDB", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "Let's Encrypt", "GitHub Actions", "Railway", "Cloudflare Workers", "VPS / Linux", "CI/CD"],
          },
          {
            name: "integrations/",
            items: ["Stripe", "Cloudinary", "Telegram Bot API", "OpenRouter", "Claude API", "Ollama", "Whisper", "JWT / OAuth 2.0", "SMTP / MailKit"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (для 3D-ассетов)", "Postman", "Sentry", "Jest", "ESLint", "Electron", "ffmpeg"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          shot: "assets/cases/villa-jaconda.jpg",
          shotAlt: "Главная страница сайта Villa Jaconda",
          context: "Свести бронирование, программу лояльности и управление в одно приложение: гость видит актуальную занятость и свои бонусы, владелец — выручку, события и начисления.",
          name: "Villa Jaconda",
          kind: "Кроссплатформенное приложение · бронирование и лояльность",
          role: "Fullstack / Lead",
          summary:
            "Мобильное приложение для сети вилл: бронирование по календарю, программа лояльности с уровнями и админ-панель с финансовой аналитикой. Полный цикл — от прототипа до сборок в сторы.",
          features: [
            "Просмотр и бронирование вилл с выбором дат через календарь",
            "Уровни лояльности Bronze → Silver → Gold → Platinum, графики трат за 6 месяцев",
            "Push-уведомления через Expo и центр уведомлений с фильтрами по типу",
            "Живые обновления без перезагрузки через Server-Sent Events",
            "История бронирований, отзывы 1–5★, светлая и тёмная темы",
            "Админ-панель: пользователи, пополнение баланса, события, аналитика выручки",
          ],
          stack: ["React Native 0.83", "Expo 55", "React Navigation", "Node.js", "Express", "Sequelize", "PostgreSQL", "JWT", "Railway", "GitHub Actions"],
          metrics: [
            { k: "253", v: "юнит-теста (Jest + supertest)" },
            { k: "2", v: "платформы: iOS + Android через EAS" },
            { k: "4", v: "уровня программы лояльности" },
          ],
          links: {
            live: "https://villajaconda.com",
            liveLabel: "сайт виллы",
            repo: "https://github.com/nekopunk44/Loyalty_app",
          },
        },
        {
          id: "avtotime",
          code: "case_02",
          context: "Автолюбитель ищет машину на одной площадке, общается на другой, готовится к экзамену на третьей. Задача — собрать три сценария в одном продукте так, чтобы не чувствовалась склейка.",
          name: "Avtotime",
          kind: "Соц-сеть + маркетплейс + обучение",
          role: "Fullstack",
          summary:
            "Социальная платформа для автомобилистов: маркетплейс объявлений, подготовка к экзамену ПДД и живое общение в реальном времени. Три продукта в одной кодовой базе.",
          features: [
            "Маркетплейс: авто, запчасти и услуги — по категориям, с оплатой через Stripe",
            "Соцсеть: лента постов, истории, подписки и реакции",
            "Реалтайм-чат и уведомления на Socket.IO",
            "Подготовка к ПДД: банк вопросов, пробные тесты, марафоны",
            "Загрузка и обработка изображений через Cloudinary",
            "AI-модерация контента с NSFW-детектом",
          ],
          stack: ["React 19", "Redux Toolkit", "Vite", "Tailwind 4", "Node.js 20", "Express 5", "MongoDB", "Redis", "Socket.IO", "Docker Compose", "Nginx", "Let's Encrypt"],
          metrics: [
            { k: "3", v: "продукта в одной платформе" },
            { k: "2", v: "отдельных фронтенда: платформа и маркет" },
            { k: "realtime", v: "чат и уведомления на Socket.IO" },
          ],
          links: {
            live: "https://avtotime.org",
            repo: "https://github.com/nekopunk44/Avtotime",
          },
        },
        {
          id: "momentumx",
          code: "case_03",
          shot: "assets/cases/momentumx.jpg",
          shotAlt: "Главный экран сайта MomentumX с анимированной WebGL-сценой",
          context: "Агентству нужен сайт, который продаёт сам: показывает уровень работ, считает цену под регион клиента и не теряет ни одной заявки.",
          name: "MomentumX",
          kind: "Сайт digital-агентства · WebGL + .NET",
          role: "Fullstack / 3D",
          summary:
            "Платформа digital-агентства: анимированный WebGL-фронтенд, backend на ASP.NET Core для приёма заявок, региональное ценообразование и задел под AI-аналитику обращений.",
          features: [
            "Hero-сцена на Three.js, скролл-анимации на GSAP и Framer Motion",
            "Калькулятор стоимости с региональными тарифами по геолокации (ipinfo.io)",
            "Приём и хранение заявок, уведомления в Telegram Bot API и на SMTP",
            "Разделы: услуги, портфолио, статистика, команда, игровые серверы",
            "Интеграция OpenRouter AI для анализа входящих обращений",
          ],
          stack: ["Next.js 16", "React 18", "TypeScript", "Tailwind", "Three.js", "GSAP", "Framer Motion", "ASP.NET Core 8", "C#", "MongoDB", "MailKit"],
          metrics: [
            { k: "130", v: "коммитов в основной ветке" },
            { k: "2", v: "рантайма в связке: Node + .NET" },
            { k: "MIT", v: "открытый исходный код" },
          ],
          links: {
            live: "https://momentumx.club",
            repo: "https://github.com/nekopunk44/MomentumX",
          },
        },
        {
          id: "aura-scanner",
          code: "case_04",
          context: "Оцифровать, распознать и подписать документ прямо с телефона — без сканера и без пересылки файлов туда-обратно.",
          name: "Aura Scanner",
          kind: "Мобильный сканер документов · Flutter",
          role: "Fullstack / Mobile",
          summary:
            "Приложение для съёмки и распознавания документов с облачной синхронизацией и отдельным модулем электронной подписи. Flutter-клиенты и backend на Express/TypeScript.",
          features: [
            "Съёмка документов и распознавание текста (OCR)",
            "Облачная синхронизация файлов между устройствами",
            "Отдельное приложение для подписи с локальным хранением подписей",
            "Авторизация: OAuth, вход через соцсети, ротация токенов",
            "Покрытие ключевых флоу авторизации автотестами и статическим анализом",
          ],
          stack: ["Flutter", "Dart", "Express", "TypeScript", "Node.js", "OAuth 2.0"],
          metrics: [
            { k: "2", v: "мобильных приложения в связке" },
            { k: "OCR", v: "распознавание + облачная синхронизация" },
            { k: "OAuth", v: "с ротацией токенов и social login" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Aura-scaner",
          },
        },
        {
          id: "quant",
          code: "case_05",
          context: "Торговая идея всегда звучит убедительно. Задача — отличать настоящее преимущество от совпадения статистикой, а не на глаз.",
          name: "AI-Quant Insights",
          kind: "Исследовательская система · данные + LLM",
          role: "Fullstack / Data",
          summary:
            "Автономный research-инструмент: превращает торговые гипотезы в проверяемые эксперименты и выносит статистический вердикт — настоящее преимущество или красивый нарратив. Не предсказывает рынок, а проверяет идеи.",
          features: [
            "Walk-forward анализ, purged cross-validation, Monte-Carlo симуляции",
            "Поправки на множественное тестирование: Deflated Sharpe, PBO",
            "Python-пайплайн знаний: транскрибация через Whisper, извлечение гипотез через LLM",
            "Четыре клиента на одном ядре: React-дашборд, Electron, Telegram-бот, Expo",
            "Paper-trading по умолчанию, kill-switch и контроль риска",
          ],
          stack: ["TypeScript", "Node.js", "Python", "PostgreSQL / TimescaleDB", "React", "Vite", "Electron", "Expo", "Whisper", "Ollama", "Claude API"],
          metrics: [
            { k: "81", v: "автотест: 59 TS-движка + 22 Python" },
            { k: "4", v: "клиента поверх одного ядра" },
            { k: "0", v: "предсказаний — только проверка гипотез" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Quant",
          },
        },
      ],
      lab: {
        cmd: "ls ~/lab --experimental",
        title: "Лаборатория",
        note: "Пет-проекты и прототипы: пробую технологии, которые потом уходят в клиентские задачи. Весь код открыт.",
        items: [
          {
            name: "Завод нарезок",
            lang: "Python",
            kind: "Пайплайн обработки видео",
            desc: "Полуавтоматический конвейер: анализирует VOD стримов по активности чата, качает только нужные фрагменты, транскрибирует и собирает вертикальные клипы 1080×1920 с субтитрами. Веб-редактор для ревью и автопостинг в YouTube и TikTok.",
            tags: ["Python", "ffmpeg", "faster-whisper", "Claude / Gemini / Ollama", "Expo"],
            repo: "https://github.com/nekopunk44/narezka",
          },
          {
            name: "ZenPulse",
            lang: "TypeScript",
            kind: "Прототип мобильного приложения",
            desc: "Приложение для медитаций на Expo Router: paywall с месячной и годовой подпиской, библиотека сессий, таймер с дыхательными паттернами и фоновым звуком, ежедневный AI-текст «Vibe of the day».",
            tags: ["Expo", "React Native", "TypeScript", "Expo Router", "AsyncStorage"],
            repo: "https://github.com/nekopunk44/ZenPulse-AI-Meditation-App-Prototype",
          },
          {
            name: "Mythory",
            lang: "JavaScript",
            kind: "Лендинг контентной платформы",
            desc: "Витрина платформы веб-новелл: тренды недели, топ-5 месяца, каталог жанров с раскрытием и лента обновлений. Компонентная архитектура по макету Figma, готова как основа под контентные продукты.",
            tags: ["React 19", "Vite", "Sass", "React Router"],
            repo: "https://github.com/nekopunk44/Mythory",
          },
        ],
        more: "весь код на github",
      },
      timeline: [
        {
          when: "2026",
          title: "Fullstack Freelance",
          org: "Независимые проекты",
          summary: "Веду проекты целиком: бриф, архитектура, код, инфраструктура, поддержка.",
          items: [
            "MomentumX — платформа digital-агентства: WebGL-фронтенд на Next.js 16 и backend на ASP.NET Core 8, калькулятор с региональными тарифами, приём заявок в Telegram и на SMTP",
            "Aura Scanner — Flutter-приложение для сканирования документов: OCR, облачная синхронизация, отдельный модуль электронной подписи",
            "AI-Quant Insights — исследовательская система: статистическая проверка гипотез на TypeScript и Python, четыре клиента поверх общего ядра",
          ],
          stack: ["Next.js", "ASP.NET Core", "Flutter", "Python", "TimescaleDB", "Docker"],
        },
        {
          when: "2025–2026",
          title: "Fullstack / Lead",
          org: "Villa Jaconda",
          summary: "Мобильное приложение сети вилл — полный цикл от прототипа до сборок в сторы.",
          items: [
            "Бронирование по календарю занятости и программа лояльности с четырьмя уровнями",
            "Админ-панель с финансовой аналитикой, живые обновления через Server-Sent Events",
            "253 юнит-теста, CI/CD на GitHub Actions, сборки под iOS и Android через EAS",
          ],
          stack: ["React Native", "Expo", "Express", "PostgreSQL", "Sequelize", "Railway"],
        },
        {
          when: "2024–2025",
          title: "Fullstack Developer",
          org: "Avtotime",
          summary: "Соцсеть, маркетплейс и подготовка к ПДД в одной кодовой базе.",
          items: [
            "Маркетплейс объявлений с оплатой через Stripe и обработкой медиа через Cloudinary",
            "Реалтайм-чат и уведомления на Socket.IO, AI-модерация контента",
            "Инфраструктура: Docker Compose, Nginx, Let's Encrypt, два отдельных фронтенда",
          ],
          stack: ["React 19", "Redux Toolkit", "Express 5", "MongoDB", "Redis", "Socket.IO"],
        },
        {
          when: "2023–2024",
          title: "Frontend Developer",
          org: "Web-студия",
          summary: "Коммерческая разработка на потоке: сайты под ключ и интеграции.",
          items: [
            "Лендинги и корпоративные сайты с нуля по макетам Figma",
            "Интернет-магазины: каталог, корзина, подключение платёжных систем",
          ],
          stack: ["React", "JavaScript", "Sass", "REST"],
        },
        {
          when: "2023",
          title: "Старт в разработке",
          org: "Self-taught → коммерция",
          summary: "От первых учебных проектов до первых оплаченных заказов.",
          items: [
            "React и Node.js, вёрстка, работа с API",
            "Первые клиенты и первый прод",
          ],
          stack: ["React", "Node.js", "Git"],
        },
      ],
      contact: {
        cmd: "./contact --send",
        title: "Напишите — отвечу в тот же день",
        body: "Обсудим задачу, сроки и бюджет. Если решим работать — подготовлю техпредложение за 1–2 дня.",
        fields: { name: "как вас зовут", email: "email для ответа", msg: "коротко о задаче" },
        send: "./send",
        success: "[ OK ] сообщение отправлено. скоро свяжусь.",
        incomplete: "[ !! ] заполните все три поля — имя, email и описание задачи.",
        error: "[ !! ] не удалось отправить. заявка не потеряна — отправьте её письмом:",
        fallback: "→ открыть письмо с вашим текстом",
      },
      footer: "собрано вручную. без шаблонов.",
    },
    en: {
      nav: ["~/home", "~/about", "~/cases", "~/lab", "~/stack", "~/process", "~/timeline", "~/faq", "~/contact"],
      heroRole: "FULLSTACK / WEB / MOBILE / 3D",
      heroTagline: "I design and ship websites, mobile apps and 3D web scenes. From idea to production — end to end.",
      heroCta: "start a chat",
      heroSecondary: "download short CV",
      status: "AVAILABLE FOR WORK",
      bootLines: [
        "[ OK ] initializing portfolio.os v2.26",
        "[ OK ] loading ./stack --fullstack",
        "[ OK ] mounting /projects ro",
        "[ OK ] spawning motion daemon",
        "[ OK ] ready. press any key to continue",
      ],
      sectionLabels: {
        about: "01 / ABOUT",
        cases: "02 / CASES",
        lab: "03 / LAB",
        stack: "04 / STACK",
        process: "05 / PROCESS",
        timeline: "06 / EXPERIENCE",
        faq: "07 / FAQ",
        contact: "08 / CONTACT",
      },
      marquee: [
        "2+ years in production",
        "fullstack · web · mobile · 3d",
        "node · .net · python",
        "idea to deploy",
        "same-day reply",
        "remote-friendly",
        "russian · english",
      ],
      process: {
        cmd: "cat ./process.md",
        title: "How I work",
        steps: [
          { n: "01", t: "Brief", d: "We scope the task, goals, constraints. I ask the right questions.", tools: "call · text · figma" },
          { n: "02", t: "Spec", d: "I deliver a technical proposal: architecture, stack, timeline, budget.", tools: "docs · roadmap" },
          { n: "03", t: "Build", d: "I ship iteratively. Weekly demos, transparent progress.", tools: "git · preview · ci" },
          { n: "04", t: "Ship", d: "Deploy, infra setup, monitoring, documentation.", tools: "docker · nginx · sentry" },
        ],
      },
      faq: {
        cmd: "grep -r 'FAQ' ./",
        title: "Frequently asked",
        items: [
          { q: "How much does a project cost?", a: "Depends on scope. Landing from $400, corporate site from $1200, mobile MVP from $2500. Final number after the brief." },
          { q: "How do payments work?", a: "30–50% upfront, the rest by milestones or on delivery. I work with a contract. SWIFT, crypto, card — whichever works." },
          { q: "What are the timelines?", a: "Landing: 1–2 weeks. Corporate site: 3–5 weeks. Mobile MVP: 6–10 weeks. Exact timeline in the proposal." },
          { q: "Do you support the project after launch?", a: "Yes. First month is free (bug fixes). After that — hourly or via monthly retainer." },
          { q: "Solo or with a team?", a: "I usually run fullstack projects solo. For bigger scope I bring a designer, QA or a second dev — but I coordinate everything." },
          { q: "Will you sign an NDA?", a: "Sure. Code stays yours; I hand over the repo and credentials at the end." },
          { q: "What languages do you speak?", a: "Russian — native. English — fluent in writing and calls (technical B2+)." },
          { q: "What if I'm not technical?", a: "That's fine. I explain things plainly, suggest options, help you choose. You bring the task and vision — I bring the engineering." },
          { q: "Can I look at your code?", a: "Yes. A good part of my work is open on GitHub — Avtotime, MomentumX, Aura Scanner and others live in public repos. You can judge the architecture, tests and commit history before we start." },
        ],
      },
      about: {
        cmd: "cat about.md",
        title: "Hi, I'm Vladislav.",
        body: [
          "Fullstack developer with 2+ years in production. I build websites, mobile apps and plug 3D models into the web.",
          "I work end-to-end: architecture, frontend, backend, infra, deploy. Backends on Node.js and .NET, data pipelines in Python, mobile on React Native and Flutter.",
          "I like problems where visuals meet engineering — interactive storefronts, product apps, marketplaces with non-trivial UX.",
          "I don't want projects to just work. I want them to leave an impression.",
        ],
        tags: ["#fullstack", "#react", "#three.js", "#react-native", "#flutter", "#dotnet", "#python", "#3d-web"],
      },
      stack: {
        cmd: "tree ./stack --depth=2",
        groups: [
          {
            name: "frontend/",
            items: ["React", "Next.js", "TypeScript", "Three.js", "React Three Fiber", "GSAP", "Framer Motion", "Tailwind", "Redux Toolkit", "Vite", "Sass"],
          },
          {
            name: "mobile/",
            items: ["React Native", "Expo", "Expo Router", "Flutter", "Dart", "EAS Build", "Reanimated", "Skia"],
          },
          {
            name: "backend/",
            items: ["Node.js", "Express", "NestJS", "Fastify", "ASP.NET Core", "C#", "Python / FastAPI", "Prisma", "Sequelize", "tRPC", "REST", "WebSockets", "Socket.IO"],
          },
          {
            name: "databases/",
            items: ["PostgreSQL", "TimescaleDB", "MongoDB", "Redis", "SQLite"],
          },
          {
            name: "devops/",
            items: ["Docker", "Docker Compose", "Nginx", "Let's Encrypt", "GitHub Actions", "Railway", "Cloudflare Workers", "VPS / Linux", "CI/CD"],
          },
          {
            name: "integrations/",
            items: ["Stripe", "Cloudinary", "Telegram Bot API", "OpenRouter", "Claude API", "Ollama", "Whisper", "JWT / OAuth 2.0", "SMTP / MailKit"],
          },
          {
            name: "tools/",
            items: ["Git", "Figma", "Blender (for 3D assets)", "Postman", "Sentry", "Jest", "ESLint", "Electron", "ffmpeg"],
          },
        ],
      },
      cases: [
        {
          id: "villa-jaconda",
          code: "case_01",
          shot: "assets/cases/villa-jaconda.jpg",
          shotAlt: "Villa Jaconda website home page",
          context: "Fold booking, the loyalty programme and back-office into one app: the guest sees real availability and their own points, the owner sees revenue, events and payouts.",
          name: "Villa Jaconda",
          kind: "Cross-platform app · booking and loyalty",
          role: "Fullstack / Lead",
          summary:
            "Mobile app for a villa network: calendar booking, a tiered loyalty program and an admin dashboard with financial analytics. Full cycle — from prototype to store builds.",
          features: [
            "Villa browsing and booking with calendar date selection",
            "Loyalty tiers Bronze → Silver → Gold → Platinum, 6-month spending charts",
            "Expo push notifications and a notification center filtered by type",
            "Live updates without reload via Server-Sent Events",
            "Booking history, 1–5★ reviews, light and dark themes",
            "Admin panel: users, balance top-ups, events, revenue analytics",
          ],
          stack: ["React Native 0.83", "Expo 55", "React Navigation", "Node.js", "Express", "Sequelize", "PostgreSQL", "JWT", "Railway", "GitHub Actions"],
          metrics: [
            { k: "253", v: "unit tests (Jest + supertest)" },
            { k: "2", v: "platforms: iOS + Android via EAS" },
            { k: "4", v: "loyalty tiers" },
          ],
          links: {
            live: "https://villajaconda.com",
            liveLabel: "villa website",
            repo: "https://github.com/nekopunk44/Loyalty_app",
          },
        },
        {
          id: "avtotime",
          code: "case_02",
          context: "A driver shops for a car on one site, talks on another, revises for the exam on a third. The task was to fold all three into one product without it feeling stitched together.",
          name: "Avtotime",
          kind: "Social network + marketplace + learning",
          role: "Fullstack",
          summary:
            "A social platform for drivers: a classifieds marketplace, driving-exam prep and real-time communication. Three products in one codebase.",
          features: [
            "Marketplace: cars, parts and services by category, payments via Stripe",
            "Social layer: posts feed, stories, follows and reactions",
            "Real-time chat and notifications on Socket.IO",
            "Traffic-law exam prep: question bank, mock tests, marathons",
            "Image upload and processing through Cloudinary",
            "AI content moderation with NSFW detection",
          ],
          stack: ["React 19", "Redux Toolkit", "Vite", "Tailwind 4", "Node.js 20", "Express 5", "MongoDB", "Redis", "Socket.IO", "Docker Compose", "Nginx", "Let's Encrypt"],
          metrics: [
            { k: "3", v: "products in one platform" },
            { k: "2", v: "separate frontends: platform and market" },
            { k: "realtime", v: "chat and notifications on Socket.IO" },
          ],
          links: {
            live: "https://avtotime.org",
            repo: "https://github.com/nekopunk44/Avtotime",
          },
        },
        {
          id: "momentumx",
          code: "case_03",
          shot: "assets/cases/momentumx.jpg",
          shotAlt: "MomentumX home screen with its animated WebGL scene",
          context: "An agency needs a site that sells on its own: it has to show the standard of the work, price by the visitor’s region and never drop an enquiry.",
          name: "MomentumX",
          kind: "Digital agency site · WebGL + .NET",
          role: "Fullstack / 3D",
          summary:
            "A digital agency platform: animated WebGL frontend, an ASP.NET Core backend for lead capture, regional pricing logic and a foundation for AI-driven lead analysis.",
          features: [
            "Three.js hero scene, scroll animations on GSAP and Framer Motion",
            "Pricing calculator with location-based regional tariffs (ipinfo.io)",
            "Lead capture and storage, notifications via Telegram Bot API and SMTP",
            "Sections: services, portfolio, stats, team, game servers",
            "OpenRouter AI integration for analyzing incoming requests",
          ],
          stack: ["Next.js 16", "React 18", "TypeScript", "Tailwind", "Three.js", "GSAP", "Framer Motion", "ASP.NET Core 8", "C#", "MongoDB", "MailKit"],
          metrics: [
            { k: "130", v: "commits on the main branch" },
            { k: "2", v: "runtimes together: Node + .NET" },
            { k: "MIT", v: "open source" },
          ],
          links: {
            live: "https://momentumx.club",
            repo: "https://github.com/nekopunk44/MomentumX",
          },
        },
        {
          id: "aura-scanner",
          code: "case_04",
          context: "Capture, recognise and sign a document straight from the phone — no scanner, no mailing files back and forth.",
          name: "Aura Scanner",
          kind: "Mobile document scanner · Flutter",
          role: "Fullstack / Mobile",
          summary:
            "An app for capturing and recognizing documents with cloud sync and a dedicated e-signature module. Flutter clients with an Express/TypeScript backend.",
          features: [
            "Document capture and text recognition (OCR)",
            "Cloud file sync across devices",
            "Separate signature app with local signature persistence",
            "Auth: OAuth, social login, token rotation",
            "Core auth flows covered by unit tests and static analysis",
          ],
          stack: ["Flutter", "Dart", "Express", "TypeScript", "Node.js", "OAuth 2.0"],
          metrics: [
            { k: "2", v: "mobile apps working together" },
            { k: "OCR", v: "recognition + cloud sync" },
            { k: "OAuth", v: "with token rotation and social login" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Aura-scaner",
          },
        },
        {
          id: "quant",
          code: "case_05",
          context: "A trading idea always sounds convincing. The task is to tell a real edge from a coincidence with statistics rather than by eye.",
          name: "AI-Quant Insights",
          kind: "Research system · data + LLM",
          role: "Fullstack / Data",
          summary:
            "An autonomous research instrument: it turns trading hypotheses into testable experiments and returns a statistical verdict — a real edge or a compelling narrative. It doesn't predict markets, it falsifies ideas.",
          features: [
            "Walk-forward analysis, purged cross-validation, Monte-Carlo simulations",
            "Multiple-testing corrections: Deflated Sharpe, PBO",
            "Python knowledge pipeline: Whisper transcription, LLM hypothesis extraction",
            "Four clients on one core: React dashboard, Electron, Telegram bot, Expo",
            "Paper trading by default, kill-switch and risk controls",
          ],
          stack: ["TypeScript", "Node.js", "Python", "PostgreSQL / TimescaleDB", "React", "Vite", "Electron", "Expo", "Whisper", "Ollama", "Claude API"],
          metrics: [
            { k: "81", v: "automated checks: 59 TS engine + 22 Python" },
            { k: "4", v: "clients on a single core" },
            { k: "0", v: "predictions — hypothesis testing only" },
          ],
          links: {
            repo: "https://github.com/nekopunk44/Quant",
          },
        },
      ],
      lab: {
        cmd: "ls ~/lab --experimental",
        title: "Lab",
        note: "Pet projects and prototypes: I try technologies here before they land in client work. All code is open.",
        items: [
          {
            name: "Clip Factory",
            lang: "Python",
            kind: "Video processing pipeline",
            desc: "A semi-automatic pipeline: it analyzes stream VODs by chat intensity, downloads only the parts that matter, transcribes them and assembles vertical 1080×1920 clips with subtitles. Local web editor for review plus auto-publishing to YouTube and TikTok.",
            tags: ["Python", "ffmpeg", "faster-whisper", "Claude / Gemini / Ollama", "Expo"],
            repo: "https://github.com/nekopunk44/narezka",
          },
          {
            name: "ZenPulse",
            lang: "TypeScript",
            kind: "Mobile app prototype",
            desc: "A meditation app on Expo Router: paywall with monthly and yearly plans, session library, timer with breathing patterns and background audio, plus a daily AI-generated \"Vibe of the day\".",
            tags: ["Expo", "React Native", "TypeScript", "Expo Router", "AsyncStorage"],
            repo: "https://github.com/nekopunk44/ZenPulse-AI-Meditation-App-Prototype",
          },
          {
            name: "Mythory",
            lang: "JavaScript",
            kind: "Content platform landing",
            desc: "A storefront for a web-novel platform: weekly trending, monthly top five, an expandable genre catalog and a latest-updates feed. Component architecture built from a Figma prototype, reusable as a base for content products.",
            tags: ["React 19", "Vite", "Sass", "React Router"],
            repo: "https://github.com/nekopunk44/Mythory",
          },
        ],
        more: "all code on github",
      },
      timeline: [
        {
          when: "2026",
          title: "Fullstack Freelance",
          org: "Independent projects",
          summary: "I run projects end to end: brief, architecture, code, infra, support.",
          items: [
            "MomentumX — digital agency platform: WebGL frontend on Next.js 16 with an ASP.NET Core 8 backend, regional pricing calculator, leads to Telegram and SMTP",
            "Aura Scanner — Flutter document scanner: OCR, cloud sync, a dedicated e-signature module",
            "AI-Quant Insights — research system: statistical hypothesis testing in TypeScript and Python, four clients on a shared core",
          ],
          stack: ["Next.js", "ASP.NET Core", "Flutter", "Python", "TimescaleDB", "Docker"],
        },
        {
          when: "2025–2026",
          title: "Fullstack / Lead",
          org: "Villa Jaconda",
          summary: "Mobile app for a villa network — full cycle from prototype to store builds.",
          items: [
            "Calendar-based booking and a four-tier loyalty program",
            "Admin dashboard with financial analytics, live updates over Server-Sent Events",
            "253 unit tests, CI/CD on GitHub Actions, iOS and Android builds via EAS",
          ],
          stack: ["React Native", "Expo", "Express", "PostgreSQL", "Sequelize", "Railway"],
        },
        {
          when: "2024–2025",
          title: "Fullstack Developer",
          org: "Avtotime",
          summary: "A social network, a marketplace and exam prep in one codebase.",
          items: [
            "Classifieds marketplace with Stripe payments and Cloudinary media processing",
            "Real-time chat and notifications on Socket.IO, AI content moderation",
            "Infrastructure: Docker Compose, Nginx, Let's Encrypt, two separate frontends",
          ],
          stack: ["React 19", "Redux Toolkit", "Express 5", "MongoDB", "Redis", "Socket.IO"],
        },
        {
          when: "2023–2024",
          title: "Frontend Developer",
          org: "Web studio",
          summary: "Commercial delivery at pace: sites built to spec, plus integrations.",
          items: [
            "Landings and corporate sites built from Figma designs",
            "E-commerce: catalogue, cart, payment provider integrations",
          ],
          stack: ["React", "JavaScript", "Sass", "REST"],
        },
        {
          when: "2023",
          title: "Dev career start",
          org: "Self-taught → commercial",
          summary: "From first practice projects to first paid work.",
          items: [
            "React and Node.js, markup, working with APIs",
            "First clients and first production deploy",
          ],
          stack: ["React", "Node.js", "Git"],
        },
      ],
      contact: {
        cmd: "./contact --send",
        title: "Say hi — I reply same day",
        body: "We'll scope the task, timeline, budget. If we're a fit, I deliver a tech proposal in 1–2 days.",
        fields: { name: "your name", email: "reply email", msg: "brief about the task" },
        send: "./send",
        success: "[ OK ] message sent. I'll get back shortly.",
        incomplete: "[ !! ] fill in all three fields — name, email and a note about the task.",
        error: "[ !! ] could not send. your message is not lost — send it as email:",
        fallback: "→ open an email with your text",
      },
      footer: "hand-built. no templates.",
    },
  },
};
